version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WS_URL=wss://api.guessthelink.com
      - NEXT_PUBLIC_API_URL=https://api.guessthelink.com
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - WS_PORT=3001
      - MAX_PLAYERS_PER_ROOM=2
      - ROUND_TIMER=20
      - MAX_GUESSES_PER_ROUND=5
      - GUESS_COOLDOWN=2000
      - CORS_ORIGIN=https://guessthelink.com
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - ./server/ssl:/usr/src/app/ssl
    restart: unless-stopped 